
REM INSERTING into DBA_JULIAN.PAISES
SET DEFINE OFF;
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Colombia','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('China','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Czech Republic','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Brazil','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Thailand','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Portugal','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Indonesia','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Cyprus','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('South Africa','1');
Insert into DBA_JULIAN.PAISES (PAIS,SOFT_DELETION) values ('Indonesia','1');

REM INSERTING into DBA_JULIAN.DEPARTAMENTOS
SET DEFINE OFF;
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Antioquia','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Cundinamarca','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Tolima','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Caldas','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Choco','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Bolivar','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Amazonas','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Sucre','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Valle del cauca','1','1');
Insert into DBA_JULIAN.DEPARTAMENTOS (DEPARTAMENTO,ID_PAIS,SOFT_DELETION) values ('Boyaca','1','1');

REM INSERTING into DBA_JULIAN.MUNICIPIOS
SET DEFINE OFF;
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Medellin','1','51050','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Bello','1','51051','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Caldas','1','51052','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Envigado','1','51053','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Itagui','1','51054','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Sabaneta','1','51055','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Copacabana','1','51056','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Girardota','1','51057','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('Guatape','1','51058','1');
Insert into DBA_JULIAN.MUNICIPIOS (MUNICIPIO,ID_DEPARTAMENTO,COD_POSTAL,SOFT_DELETION) values ('La Estrella','1','51059','1');


REM INSERTING into DBA_JULIAN.PREFIJOS
SET DEFINE OFF;
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+591','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+55','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+57','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+593','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+595','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+51','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+598','1');
Insert into DBA_JULIAN.PREFIJOS (PREFIJO,SOFT_DELETION) values ('+58','1');



REM INSERTING into DBA_JULIAN.USUARIOS
SET DEFINE OFF;
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('231140781','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/83','DD/MM/RR'),'COLOMBIANA','Dorthea','Berenice','Bridywater','Shilstone',to_date('15/05/83','DD/MM/RR'),'Medovene','275 Spohn Crossing','27 Lillian Terrace','SFgHsgaKE6X','bshilstone0@craigslist.org','ESPANOL','9868321760','1','1','SENOR','\DOCUMENTOS\DOC1','1','0','1','3','10');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('4961195126','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/84','DD/MM/RR'),'COLOMBIANA','Mady','Valene','Halpen','Westrip',to_date('15/05/84','DD/MM/RR'),'Medovene','2342 Eagle Crest Place','82 Mifflin Way','tMfFxQY','vwestrip1@independent.co.uk','ESPANOL','2634359788','1','1','SENORA','\DOCUMENTOS\DOC2','0','0','2','3','15');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('65186117207','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/85','DD/MM/RR'),'COLOMBIANA','Elmira','Quinton','Elgram','Rendall',to_date('15/05/85','DD/MM/RR'),'Vyshneve','609 Anniversary Hill','5158 Lakeland Court','6Opj3af2Mn4','qrendall2@ow.ly','ESPANOL','5894800821','1','1','SENOR','\DOCUMENTOS\DOC3','1','0','3','3','12');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('18250145251','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/86','DD/MM/RR'),'COLOMBIANA','Granger','Traver','Aubert','Muckeen',to_date('15/05/86','DD/MM/RR'),'Kadoma','03100 Kropf Court','3 Haas Road','dvU6he','tmuckeen3@hostgator.com','ESPANOL','6579894423','1','1','SENORA','\DOCUMENTOS\DOC4','1','0','4','3','8');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('1602098144','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/87','DD/MM/RR'),'COLOMBIANA','Carola','Carey','Turbayne','Tefft',to_date('15/05/87','DD/MM/RR'),'Yuzhno-Sukhokumsk','56165 Alpine Alley','45 Sachtjen Plaza','ILIIJKWhmgf','ctefft4@bloomberg.com','ESPANOL','7347025197','1','1','SENOR','\DOCUMENTOS\DOC5','1','0','5','3','9');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('5338165141','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/88','DD/MM/RR'),'COLOMBIANA','Sydelle','Marni','Komorowski','Thewless',to_date('15/05/88','DD/MM/RR'),'Kete Krachi','67140 Kipling Lane','16 Clemons Trail','aioIBHf','mthewless5@mlb.com','ESPANOL','5539863158','1','1','SENORA','\DOCUMENTOS\DOC6','1','0','6','3','5');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('140816821','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/89','DD/MM/RR'),'COLOMBIANA','Adelle','Anetta','Fludder','Reichhardt',to_date('15/05/89','DD/MM/RR'),'Menlouâ€™ao','196 International Point','8413 Melody Parkway','LIUKOH73FZ','areichhardt6@g.co','ESPANOL','5708910001','1','1','SENOR','\DOCUMENTOS\DOC7','1','0','1','3','5');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('676230196','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/90','DD/MM/RR'),'COLOMBIANA','Johan','Darrell','Dressel','Prewett',to_date('15/05/90','DD/MM/RR'),'Ban Thaen','66 Grover Crossing','9 Mccormick Avenue','5z4lQkWkn','dprewett7@tiny.cc','ESPANOL','8584529844','1','1','SENORA','\DOCUMENTOS\DOC8','1','0','2','3','5');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('102983542','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/91','DD/MM/RR'),'COLOMBIANA','Terri-jo','Mufi','Caplis','Simchenko',to_date('15/05/91','DD/MM/RR'),'Le Mans','385 Dawn Crossing','380 Dakota Drive','lRGMvUWoZvR','msimchenko8@hatena.ne.jp','ESPANOL','2104595749','1','1','SENOR','\DOCUMENTOS\DOC9','1','0','3','3','17');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('72148212209','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/92','DD/MM/RR'),'COLOMBIANA','Donnie','Massimiliano','Cottom','Jiracek',to_date('15/05/92','DD/MM/RR'),'GrÃ¤storp','688 Artisan Hill','394 Mandrake Road','crSytY','mjiracek9@bandcamp.com','ESPANOL','9336610673','1','1','SENORA','\DOCUMENTOS\DOC10','1','0','4','3','12');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('278967132','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/93','DD/MM/RR'),'COLOMBIANA','Arleen','Gery','Rooson','Donisi',to_date('15/05/93','DD/MM/RR'),'GoÅ‚kowice','4 Lakewood Gardens Lane','24 Hovde Road','YCmphusGwYIh','gdonisia@constantcontact.com','ESPANOL','4584722365','1','1','SENOR','\DOCUMENTOS\DOC11','1','0','5','3','10');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('1913023939','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/94','DD/MM/RR'),'COLOMBIANA','Sharai','Cecilius','Adrain','Gilson',to_date('15/05/94','DD/MM/RR'),'Orikum','495 Troy Trail','486 Arkansas Center','70DTL4aLyjCJ','cgilsonb@sohu.com','ESPANOL','3793375421','1','1','SENORA','\DOCUMENTOS\DOC12','1','0','6','3','10');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('191902510','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/95','DD/MM/RR'),'COLOMBIANA','Benedict','Cacilia','Duligall','Kalderon',to_date('15/05/95','DD/MM/RR'),'Hallstahammar','63255 Harper Way','688 Dapin Junction','81bbmyrRT','ckalderonc@networkadvertising.org','ESPANOL','9389361486','1','1','SENOR','\DOCUMENTOS\DOC13','1','0','1','3','10');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('25120939147','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/96','DD/MM/RR'),'COLOMBIANA','Gerome','Lucky','Metzing','Liggett',to_date('15/05/96','DD/MM/RR'),'KemijÃ¤rvi','92284 Hollow Ridge Crossing','4168 Hintze Road','rFx0hNP','lliggettd@amazon.de','ESPANOL','9194364372','1','1','SENORA','\DOCUMENTOS\DOC14','1','0','2','3','12');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('4317719670','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/97','DD/MM/RR'),'COLOMBIANA','Demetra','Ronald','Gronaver','Cosely',to_date('15/05/97','DD/MM/RR'),'Mingoyo','452 Superior Way','63766 Mayer Drive','QSeTJiX9t','rcoselye@youtube.com','ESPANOL','1542203811','1','1','SENOR','\DOCUMENTOS\DOC15','1','0','3','3','12');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('138278206','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/83','DD/MM/RR'),'COLOMBIANA','Jemima','Gabe','Hawkey','Trousdell',to_date('15/05/83','DD/MM/RR'),'Priupskiy','9 Armistice Court','0413 Macpherson Street','YGdF3xTuQ','gtrousdellf@symantec.com','ESPANOL','5918933420','1','1','SENORA','\DOCUMENTOS\DOC16','1','0','4','3','12');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('3116010411','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/84','DD/MM/RR'),'COLOMBIANA','Timmy','Joela','Wollard','Pride',to_date('15/05/84','DD/MM/RR'),'Forquilhinha','4747 Tennessee Pass','72 Morningstar Crossing','9cwrvRCTe6zv','jprideg@tmall.com','ESPANOL','5464166456','1','1','SENOR','\DOCUMENTOS\DOC17','1','0','5','3','13');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('21713523750','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/85','DD/MM/RR'),'COLOMBIANA','Bogart','Augustina','Spear','Mealiffe',to_date('15/05/85','DD/MM/RR'),'Palikir - National Government Center','48 Sachtjen Street','72 Waxwing Plaza','aeWRCbJUl','amealiffeh@techcrunch.com','ESPANOL','5033972326','1','1','SENORA','\DOCUMENTOS\DOC18','1','0','6','3','8');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('22522811979','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/86','DD/MM/RR'),'COLOMBIANA','Bethina','Lynnette','Shellshear','Whoolehan',to_date('15/05/86','DD/MM/RR'),'Lucapon','0 Delladonna Terrace','65 Orin Point','V1nyLa0gM','lwhoolehani@scientificamerican.com','ESPANOL','5457677882','1','1','SENOR','\DOCUMENTOS\DOC19','1''1','3','8');
Insert into DBA_JULIAN.USUARIOS (DOCUMENTO,TIPO_DOCUMENTO,LUGAR_EXPEDICION,FECHA_EXPEDICION,NACIONALIDAD,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_DE_NACIMIENTO,LUGAR_NACIMIENTO,DICRECCION,DIRECCION2,CONTRASENA,EMAIL,IDIOMA_EMAIL,CELULAR,TERMINOS,RECIBIR_INFO,TITULO,RUTA_DOCUMENTOS,SOFT_DELETION,SALDO,ID_MUNICIPIO,ID_PREFIJO,HORAS_SESION) values ('18493164155','CEDULA CIUDADANIA','MEDELLIN',to_date('15/05/87','DD/MM/RR'),'COLOMBIANA','Aleece','Leonie','Goodram','Gornar',to_date('15/05/87','DD/MM/RR'),'Pakembangan','4618 Russell Avenue','121 Arrowood Pass','YVEkgz72hhA','lgornarj@intel.com','ESPANOL','4286434434','1','1','SENORA','\DOCUMENTOS\DOC20','1','0','2','3','6');



REM INSERTING into DBA_JULIAN.BONOS
SET DEFINE OFF;
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200050',to_date('19/07/19','DD/MM/RR'),to_date('20/07/19','DD/MM/RR'),'1','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200051',to_date('20/07/19','DD/MM/RR'),to_date('21/07/19','DD/MM/RR'),'2','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200052',to_date('21/07/19','DD/MM/RR'),to_date('22/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200053',to_date('22/07/19','DD/MM/RR'),to_date('23/07/19','DD/MM/RR'),'4','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200054',to_date('23/07/19','DD/MM/RR'),to_date('24/07/19','DD/MM/RR'),'5','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200055',to_date('24/07/19','DD/MM/RR'),to_date('25/07/19','DD/MM/RR'),'6','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200056',to_date('25/07/19','DD/MM/RR'),to_date('26/07/19','DD/MM/RR'),'7','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200057',to_date('26/07/19','DD/MM/RR'),to_date('27/07/19','DD/MM/RR'),'8','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200058',to_date('27/07/19','DD/MM/RR'),to_date('28/07/19','DD/MM/RR'),'9','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200059',to_date('28/07/19','DD/MM/RR'),to_date('29/07/19','DD/MM/RR'),'10','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200060',to_date('29/07/19','DD/MM/RR'),to_date('30/07/19','DD/MM/RR'),'11','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200061',to_date('30/07/19','DD/MM/RR'),to_date('31/07/19','DD/MM/RR'),'12','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200062',to_date('31/07/19','DD/MM/RR'),to_date('01/08/19','DD/MM/RR'),'13','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200063',to_date('01/08/19','DD/MM/RR'),to_date('02/08/19','DD/MM/RR'),'14','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200064',to_date('02/08/19','DD/MM/RR'),to_date('03/08/19','DD/MM/RR'),'15','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200065',to_date('03/08/19','DD/MM/RR'),to_date('04/08/19','DD/MM/RR'),'16','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200066',to_date('04/08/19','DD/MM/RR'),to_date('05/08/19','DD/MM/RR'),'17','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200067',to_date('05/08/19','DD/MM/RR'),to_date('06/08/19','DD/MM/RR'),'18','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200068',to_date('06/08/19','DD/MM/RR'),to_date('07/08/19','DD/MM/RR'),'19','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200069',to_date('07/08/19','DD/MM/RR'),to_date('08/08/19','DD/MM/RR'),'20','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200050',to_date('19/07/19','DD/MM/RR'),to_date('20/07/19','DD/MM/RR'),'1','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200051',to_date('20/07/19','DD/MM/RR'),to_date('21/07/19','DD/MM/RR'),'2','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200052',to_date('21/07/19','DD/MM/RR'),to_date('22/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200053',to_date('22/07/19','DD/MM/RR'),to_date('23/07/19','DD/MM/RR'),'4','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200054',to_date('23/07/19','DD/MM/RR'),to_date('24/07/19','DD/MM/RR'),'5','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200055',to_date('24/07/19','DD/MM/RR'),to_date('25/07/19','DD/MM/RR'),'6','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200056',to_date('25/07/19','DD/MM/RR'),to_date('26/07/19','DD/MM/RR'),'7','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200057',to_date('26/07/19','DD/MM/RR'),to_date('27/07/19','DD/MM/RR'),'8','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200058',to_date('27/07/19','DD/MM/RR'),to_date('28/07/19','DD/MM/RR'),'9','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200059',to_date('28/07/19','DD/MM/RR'),to_date('29/07/19','DD/MM/RR'),'10','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200060',to_date('29/07/19','DD/MM/RR'),to_date('30/07/19','DD/MM/RR'),'1','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200061',to_date('30/07/19','DD/MM/RR'),to_date('31/07/19','DD/MM/RR'),'2','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200062',to_date('31/07/19','DD/MM/RR'),to_date('01/08/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200063',to_date('01/08/19','DD/MM/RR'),to_date('02/08/19','DD/MM/RR'),'4','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200064',to_date('02/08/19','DD/MM/RR'),to_date('03/08/19','DD/MM/RR'),'5','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200065',to_date('03/08/19','DD/MM/RR'),to_date('04/08/19','DD/MM/RR'),'6','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200066',to_date('04/08/19','DD/MM/RR'),to_date('05/08/19','DD/MM/RR'),'7','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200067',to_date('05/08/19','DD/MM/RR'),to_date('06/08/19','DD/MM/RR'),'8','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200068',to_date('06/08/19','DD/MM/RR'),to_date('07/08/19','DD/MM/RR'),'9','1');
Insert into DBA_JULIAN.BONOS (CODIGO_BONO,FECHA_INICIO,FECHA_FIN,ID_USUARIO,SOFT_DELETION) values ('200069',to_date('07/08/19','DD/MM/RR'),to_date('08/08/19','DD/MM/RR'),'10','1');

REM INSERTING into DBA_JULIAN.PREFERENCIAS
SET DEFINE OFF;
Insert into DBA_JULIAN.PREFERENCIAS (PREFERENCIA,SOFT_DELETION) values ('BOLETIN INFORMATIVO','1');
Insert into DBA_JULIAN.PREFERENCIAS (PREFERENCIA,SOFT_DELETION) values ('CORREOS DE APUESTAS DEPORTIVAS','1');
Insert into DBA_JULIAN.PREFERENCIAS (PREFERENCIA,SOFT_DELETION) values ('ENVIO DE SMS','1');
Insert into DBA_JULIAN.PREFERENCIAS (PREFERENCIA,SOFT_DELETION) values ('NOTIFICACIONES DEL NAVEGADOR','1');
Insert into DBA_JULIAN.PREFERENCIAS (PREFERENCIA,SOFT_DELETION) values ('AVISO DE BOLETO DE APUESTA','1');


REM INSERTING into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS
SET DEFINE OFF;
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('1','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('1','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('1','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('1','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('1','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('2','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('2','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('2','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('2','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('2','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('3','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('3','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('3','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('3','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('3','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('4','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('4','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('4','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('4','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('4','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('5','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('5','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('5','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('5','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('5','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('6','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('6','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('6','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('6','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('6','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('7','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('7','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('7','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('7','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('7','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('8','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('8','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('8','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('8','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('8','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('9','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('9','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('9','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('9','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('9','5','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('10','1','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('10','2','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('10','3','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('10','4','1');
Insert into DBA_JULIAN.PREFERENCIAS_DE_USUARIOS (ID_USUARIO,ID_PREFERENCIA,SOFT_DELETION) values ('10','5','1');


REM INSERTING into DBA_JULIAN.LIMITES
SET DEFINE OFF;
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('200000','600000','1800000',to_timestamp('24/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'1','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('300000','900000','2700000',to_timestamp('25/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'2','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('400000','1200000','3600000',to_timestamp('26/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'3','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('500000','1500000','4500000',to_timestamp('24/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'4','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('600000','1800000','5400000',to_timestamp('25/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'5','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('700000','2100000','6300000',to_timestamp('26/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'6','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('800000','2400000','7200000',to_timestamp('24/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'7','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('900000','2700000','8100000',to_timestamp('25/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'8','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('200000','600000','1800000',to_timestamp('26/11/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'9','1');
Insert into DBA_JULIAN.LIMITES (LIMITE_DIA,LIMITE_SEMANA,LIMITE_MES,FECHA_MODIFICACION,ID_USUARIO,SOFT_DELETION) values ('300000','900000','2700000',to_timestamp('03/12/19 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'10','1');


REM INSERTING into DBA_JULIAN.ESTADOS_DEPOSITOS
SET DEFINE OFF;
Insert into DBA_JULIAN.ESTADOS_DEPOSITOS (ESTADO,SOFT_DELETION) values ('PENDIENTE','1');
Insert into DBA_JULIAN.ESTADOS_DEPOSITOS (ESTADO,SOFT_DELETION) values ('EN PROCESO','1');
Insert into DBA_JULIAN.ESTADOS_DEPOSITOS (ESTADO,SOFT_DELETION) values ('RECHAZADA','1');
Insert into DBA_JULIAN.ESTADOS_DEPOSITOS (ESTADO,SOFT_DELETION) values ('EXITOSO','1');



REM INSERTING into DBA_JULIAN.MEDIOS_DE_PAGO
SET DEFINE OFF;
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('Visa-Mastercard','20000','36000000','1');
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('Baloto','18000','100000000','1');
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('PSE','18000','100000000','1');
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('Punto Red','1000','1000000','1');
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('Efecty','5000','100000000','1');
Insert into DBA_JULIAN.MEDIOS_DE_PAGO (MEDIO_DE_PAGO,VALOR_MINIMO,VALOR_MAXIMO,SOFT_DELETION) values ('Dimonex','5000','3000000','1');



REM INSERTING into DBA_JULIAN.DEPOSITOS
SET DEFINE OFF;
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('50000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'1','1','1','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('70000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'2','2','2','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('90000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'3','3','3','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('110000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'4','4','4','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('130000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'5','1','5','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('150000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'6','2','6','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('170000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'7','3','1','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('190000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'8','4','2','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('210000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'9','1','3','1');
Insert into DBA_JULIAN.DEPOSITOS (VALOR,FECHA,ID_USUARIO,ID_ESTADO,ID_MEDIO_DE_PAGO,SOFT_DELETION) values ('230000',to_timestamp('05/02/08 06:12:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'10','2','4','1');



REM INSERTING into DBA_JULIAN.COMPROBANTES
SET DEFINE OFF;
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA1','50','.PNG','\COMPROBANTE\COMPROBANTE1','50','.PNG','\IDENTIFICACION\IDENTIFICACION1','50','.PNG','\FOTO\FOTO1','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA2','50','.PNG','\COMPROBANTE\COMPROBANTE2','50','.PNG','\IDENTIFICACION\IDENTIFICACION2','50','.PNG','\FOTO\FOTO2','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA3','50','.PNG','\COMPROBANTE\COMPROBANTE3','50','.PNG','\IDENTIFICACION\IDENTIFICACION3','50','.PNG','\FOTO\FOTO3','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA4','50','.PNG','\COMPROBANTE\COMPROBANTE4','50','.PNG','\IDENTIFICACION\IDENTIFICACION4','50','.PNG','\FOTO\FOTO4','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA5','50','.PNG','\COMPROBANTE\COMPROBANTE5','50','.PNG','\IDENTIFICACION\IDENTIFICACION5','50','.PNG','\FOTO\FOTO5','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA6','50','.PNG','\COMPROBANTE\COMPROBANTE6','50','.PNG','\IDENTIFICACION\IDENTIFICACION6','50','.PNG','\FOTO\FOTO6','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA7','50','.PNG','\COMPROBANTE\COMPROBANTE7','50','.PNG','\IDENTIFICACION\IDENTIFICACION7','50','.PNG','\FOTO\FOTO7','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA8','50','.PNG','\COMPROBANTE\COMPROBANTE8','50','.PNG','\IDENTIFICACION\IDENTIFICACION8','50','.PNG','\FOTO\FOTO8','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA9','50','.PNG','\COMPROBANTE\COMPROBANTE9','50','.PNG','\IDENTIFICACION\IDENTIFICACION9','50','.PNG','\FOTO\FOTO9','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA10','50','.PNG','\COMPROBANTE\COMPROBANTE10','50','.PNG','\IDENTIFICACION\IDENTIFICACION10','50','.PNG','\FOTO\FOTO10','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA11','50','.PNG','\COMPROBANTE\COMPROBANTE11','50','.PNG','\IDENTIFICACION\IDENTIFICACION11','50','.PNG','\FOTO\FOTO11','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA12','50','.PNG','\COMPROBANTE\COMPROBANTE12','50','.PNG','\IDENTIFICACION\IDENTIFICACION12','50','.PNG','\FOTO\FOTO12','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA13','50','.PNG','\COMPROBANTE\COMPROBANTE13','50','.PNG','\IDENTIFICACION\IDENTIFICACION13','50','.PNG','\FOTO\FOTO13','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA14','50','.PNG','\COMPROBANTE\COMPROBANTE14','50','.PNG','\IDENTIFICACION\IDENTIFICACION14','50','.PNG','\FOTO\FOTO14','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA15','50','.PNG','\COMPROBANTE\COMPROBANTE15','50','.PNG','\IDENTIFICACION\IDENTIFICACION15','50','.PNG','\FOTO\FOTO15','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA16','50','.PNG','\COMPROBANTE\COMPROBANTE16','50','.PNG','\IDENTIFICACION\IDENTIFICACION16','50','.PNG','\FOTO\FOTO16','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA17','50','.PNG','\COMPROBANTE\COMPROBANTE17','50','.PNG','\IDENTIFICACION\IDENTIFICACION17','50','.PNG','\FOTO\FOTO17','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA18','50','.PNG','\COMPROBANTE\COMPROBANTE18','50','.PNG','\IDENTIFICACION\IDENTIFICACION18','50','.PNG','\FOTO\FOTO18','50','.PNG','1');
Insert into DBA_JULIAN.COMPROBANTES (FACTURA_SERVICIOS,TAMANO_FACTURA_SERVICIOS,EXTENSION_FACTURA_SERVICIOS,COMPROBANTE_DEPOSITO,TAMANO_COMPROBANTE_DEPOSITO,EXTENSION_COMPROBANTE_DEPOSITO,IDENTIFICACION,TAMANO_IDENTIFICACION,EXTENSION_IDENTIFICACION,FOTO_PERSONAL,TAMANO_FOTO_PERSONAL,EXTENSION_FOTO_PERSONAL,SOFT_DELETION) values ('\FACTURA\FACTURA19','50','.PNG','\COMPROBANTE\COMPROBANTE19','50','.PNG','\IDENTIFICACION\IDENTIFICACION19','50','.PNG','\FOTO\FOTO19','50','.PNG','1');


REM INSERTING into DBA_JULIAN.RETIROS
SET DEFINE OFF;
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCOLOMBIA','56487764532','0','1','1','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'DAVIVIENDA','56487764533','0','2','2','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCO AGRARIO','56487764534','0','3','3','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCO DE BOGOTA','56487764535','0','4','4','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCOLOMBIA','56487764536','0','5','5','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'DAVIVIENDA','56487764537','0','6','6','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCO AGRARIO','56487764538','0','7','7','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCO DE BOGOTA','56487764539','0','8','8','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'BANCOLOMBIA','56487764540','0','9','9','1');
Insert into DBA_JULIAN.RETIROS (VALOR_RETIRO,FECHA_SOLICITUD,FECHA_DESEMBOLSO,BANCO,CUENTA_BANCARIA,REQUISITO,ID_USUARIO,ID_COMPROBANTE,SOFT_DELETION) values ('0',to_timestamp('06/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('07/06/08 06:30:00,000000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),'DAVIVIENDA','56487764541','0','10','10','1');



REM INSERTING into DBA_JULIAN.EQUIPOS
SET DEFINE OFF;
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Atlético Nacional','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Millonarios','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('América de Cali','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Santa Fe','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Deportivo Cali','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Junior','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Independiente Medellín','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Once Caldas','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Deportes Tolima','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Cúcuta Deportivo','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Deportivo Pasto','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Unión Magdalena','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('La Equidad','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Atlético Bucaramanga','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Atlético Huila','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Envigado F. C.','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Rionegro Águilas','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Alianza Petrolera','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Jaguares','1');
Insert into DBA_JULIAN.EQUIPOS (EQUIPO,SOFT_DELETION) values ('Patriotas','1');

REM INSERTING into DBA_JULIAN.PARTIDOS
SET DEFINE OFF;
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('1','2','1','0','1','0','1','1','1','FINALIZADO',to_date('19/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('3','4','0','1','0','1','1','4','4','FINALIZADO',to_date('20/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('5','6','1','0','2','0','2','5','5','FINALIZADO',to_date('21/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('7','8','0','1','0','2','2','8','8','FINALIZADO',to_date('22/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('9','10','2','0','3','0','3','9','9','FINALIZADO',to_date('23/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('11','12','0','1','0','1','1','12','12','FINALIZADO',to_date('24/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('13','14','1','0','1','2','3','13','14','EN CURSO',to_date('25/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('15','16','2','0','2','0','2','15','15','EN CURSO',to_date('26/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('17','18','3','0','3','0','3','17','17','EN CURSO',to_date('27/11/19','DD/MM/RR'),'1');
Insert into DBA_JULIAN.PARTIDOS (ID_LOCAL,ID_VISITANTE,GOLES_L_PT,GOLES_V_PT,TOTAL_GOLES_L,TOTAL_GOLES_V,TOTAL_GOLES_PARTIDO,ID_GANADOR_PT,ID_GANADOR_ST,ESTADO,FECHA,SOFT_DELETION) values ('19','20','0','1','2','1','3','20','19','NO INICIADO',to_date('28/11/19','DD/MM/RR'),'1');

REM INSERTING into DBA_JULIAN.CATEGORIAS
SET DEFINE OFF;
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('MAS/MENOS(1.5)','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('MAS/MENOS(0.5)','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('MAS/MENOS(2.5)','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('MAS/MENOS(3.5)','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('AMBOS EQUIPOS ANOTARAN GOL','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('QUIEN GANARA EL PRIMER TIEMPO','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('QUIEN GANARA EL SEGUNDO TIEMPO','1');
Insert into DBA_JULIAN.CATEGORIAS (NOMBRE,SOFT_DELETION) values ('HAY POR LO MENOS UN GOL EN CADA TIEMPO','1');


REM INSERTING into DBA_JULIAN.CUOTAS
SET DEFINE OFF;
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.6','2.3','2.3','TERMINADO','1','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.12','6.3','1.12','TERMINADO','2','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.7','1.45','1.45','TERMINADO','3','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'6','1.13','1.13','TERMINADO','4','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.2','1.6','1.6','TERMINADO','5','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.9','1.85','4.3','2.9','TERMINADO','6','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.55','2.1','3.9','2.55','TERMINADO','7','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.3','1.55','1.55','TERMINADO','8','1','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.6','2.3','2.3','TERMINADO','1','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.12','6.3','1.12','TERMINADO','2','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.7','1.45','1.45','TERMINADO','3','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'6','1.13','1.13','TERMINADO','4','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.2','1.6','1.6','TERMINADO','5','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.9','1.85','4.3','4.3','TERMINADO','6','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.55','2.1','3.9','3.9','TERMINADO','7','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.3','1.55','1.55','TERMINADO','8','2','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.6','2.3','1.6','TERMINADO','1','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.12','6.3','1.12','TERMINADO','2','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.7','1.45','1.45','TERMINADO','3','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'6','1.13','1.13','TERMINADO','4','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.2','1.6','1.6','TERMINADO','5','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.9','1.85','4.3','2.9','TERMINADO','6','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.55','2.1','3.9','2.55','TERMINADO','7','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.3','1.55','2.3','TERMINADO','8','3','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.6','2.3','1.6','TERMINADO','1','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'1.12','6.3','1.12','TERMINADO','2','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.7','1.45','1.45','TERMINADO','3','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'6','1.13','1.13','TERMINADO','4','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.2','1.6','1.6','TERMINADO','5','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.9','1.85','4.3','4.3','TERMINADO','6','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values ('2.55','2.1','3.9','3.9','TERMINADO','7','4','1');
Insert into DBA_JULIAN.CUOTAS (OPCION1,OPCION2,OPCION3,CUOTA_GANADORA,ESTADO,ID_CATEGORIA,ID_PARTIDO,SOFT_DELETION) values (null,'2.3','1.55','2.3','TERMINADO','8','4','1');

REM INSERTING into DBA_JULIAN.ESTADOS
SET DEFINE OFF;
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Abierta','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Ganada','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Perdida','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Vendida','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Cancelada','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Reembolsada','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Inválida','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Rechazado','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Pedido','1');
Insert into DBA_JULIAN.ESTADOS (ESTADO,SOFT_DELETION) values ('Parte-aprobada','1');




REM INSERTING into DBA_JULIAN.APUESTAS
SET DEFINE OFF;
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('1','200000','136000',to_date('18/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('2','400000','258000',to_date('20/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('1','200000','157500',to_date('24/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('2','400000','820000',to_date('19/07/19','DD/MM/RR'),'2','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('3','200000','136000',to_date('21/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('4','400000','450000',to_date('22/07/19','DD/MM/RR'),'2','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('3','200000','136000',to_date('25/07/19','DD/MM/RR'),'3','1');
Insert into DBA_JULIAN.APUESTAS (ID_USUARIO,VALOR_TOTAL,TOTAL_GANANCIAS,FECHA,ID_ESTADO,SOFT_DELETION) values ('4','400000','820000',to_date('19/07/19','DD/MM/RR'),'2','1');



REM INSERTING into DBA_JULIAN.DETALLES_APUESTAS
SET DEFINE OFF;
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,6','1,6','GANADO','50000','1','1','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,12','1,12','GANADO','50000','1','2','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,7','1,45','PERDIDO','50000','1','3','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('6','1,13','PERDIDO','50000','1','4','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,3','1,6','PERDIDO','100000','2','1','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('6,3','1,12','PERDIDO','100000','2','2','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,45','1,45','GANADO','100000','2','3','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,13','1,13','GANADO','100000','2','4','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,6','1,6','GANADO','50000','3','13','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,9','4,3','PERDIDO','50000','3','14','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,55','3,9','PERDIDO','50000','3','15','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,55','1,55','GANADO','50000','3','16','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,2','1,6','PERDIDO','100000','4','13','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('4,3','4,3','GANADO','100000','4','14','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('3,9','3,9','GANADO','100000','4','15','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,3','1,55','PERDIDO','100000','4','16','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,6','1,6','GANADO','50000','5','17','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,12','1,12','GANADO','50000','5','18','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,7','1,45','PERDIDO','50000','5','19','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('6','1,13','PERDIDO','50000','5','20','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,6','1,6','GANADO','100000','6','21','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,9','2,9','GANADO','100000','6','22','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('3,9','2,55','PERDIDO','100000','6','23','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,55','2,3','PERDIDO','100000','6','24','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,6','1,6','GANADO','50000','7','25','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,12','1,12','GANADO','50000','7','26','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,7','1,45','PERDIDO','50000','7','27','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('6','1,13','PERDIDO','50000','7','28','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('2,2','1,6','PERDIDO','100000','8','29','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('4,3','4,3','GANADO','100000','8','30','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('3,9','3,9','GANADO','100000','8','31','1');
Insert into DBA_JULIAN.DETALLES_APUESTAS (OPCION_CUOTA,CUOTA_GANADORA,ESTADO,VALOR_APOSTADO,ID_APUESTA,ID_CUOTA,SOFT_DELETION) values ('1,55','2,3','PERDIDO','100000','8','32','1');

SELECT * FROM SESIONES

Insert into DBA_JULIAN.SESIONES (INICIO_SESION,FIN_SESION,ESTADO_CONEXION,ID_USUARIO,SOFT_DELETION) values (CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1,1,1);
